-- Insert the 5 missing students into the database
-- Run this in Supabase SQL Editor

INSERT INTO public.students (
  name, email, phone, course, reg_date, reg_time, payment_plan,
  amount_paid, balance_remaining, status, timestamp, gender,
  state_of_residence, learning_track, how_did_you_hear,
  has_laptop_and_internet, current_employment_status,
  wants_scholarship, why_learn_this_skill
) VALUES 
(
  'ZAINAB YUSRAH SANI',
  'zaynabyusrahsani@gmail.com',
  '07025219606',
  'Cybersecurity',
  '2/5/2026',
  '7:25:00',
  'Not Paid Yet',
  0,
  50000,
  'None',
  '2/5/2026 7:25:00',
  'Female',
  'Kano',
  'Cybersecurity',
  'Instagram',
  'Yes',
  'Student',
  'Yes',
  'Yes, I would like to apply for a scholarship. I want to be able to protect myself, the tech community and nation as a whole from cyber attack'
),
(
  'Farhaat Timehin',
  'timehinfarhaat@gmail.com',
  '+2349060321594',
  '3D Animation',
  '2/5/2026',
  '7:25:00',
  'Not Paid Yet',
  0,
  50000,
  'None',
  '2/5/2026 7:25:00',
  'Female',
  'Ogun state',
  '3D Animation',
  'Facebook',
  'Yes',
  'Student',
  'Yes',
  'Yes, I would like to apply for a scholarship. I want to learn this skill to achieve financial independence by producing high-quality short films. My goal is to create engaging content, including moral-based stories and short-form comedies, that connects with viewers around the world. By building a diverse portfolio, I plan to make money through social media content creation, freelance animation services, and the sale of custom 3D assets. Ultimately, I want to use these skills to build a sustainable career and explore the many commercial opportunities in the digital animation industry.'
),
(
  'David Ezekiel',
  'siredave1@gmail.com',
  '08164707958',
  'Ai Automation',
  '2/5/2026',
  '7:25:00',
  'Not Paid Yet',
  0,
  50000,
  'None',
  '2/5/2026 7:25:00',
  'Male',
  'Lagos',
  'Ai Automation',
  'Instagram',
  'Yes',
  'Graduate',
  'Yes',
  'Yes, I would like to apply for a scholarship. I want to learn AI automation because it allows me to build systems that don''t just work, but work independently and efficiently. I''m driven by the idea of reducing manual effort, improving productivity, and creating solutions that can scale and solve real problems. It aligns perfectly with my technical background and my goal of building impactful, future focused products.'
),
(
  'Oladiipo Olabisi',
  'olabisi5858@gmail.com',
  '08139605858',
  'digital marketing',
  '2/5/2026',
  '7:25:00',
  'Not Paid Yet',
  0,
  50000,
  'None',
  '2/5/2026 7:25:00',
  'Female',
  'Ibadan',
  'digital marketing',
  'Facebook',
  'Yes',
  'Self Employed',
  'Yes',
  'Yes, I would like to apply for a scholarship. I want to have a new tech skills'
),
(
  'Nafisat Kuforiji Omonike',
  'kuforijinafisat8@gmail.com',
  '09032960253',
  'Graphic Design',
  '2/5/2026',
  '7:25:00',
  'Not Paid Yet',
  0,
  50000,
  'None',
  '2/5/2026 7:25:00',
  'Female',
  'Lagos',
  'Graphic Design',
  'Facebook',
  'Yes',
  'Unemployed',
  'Yes',
  'Yes, I would like to apply for a scholarship. I want to learn this skill because I love creativity.'
);
